In [6]:
%pip install pandas

Collecting pandas
  Downloading pandas-3.0.6-cp313-cp313-macosx_11_0_arm64.whl.metadata (79 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.5.3-cp313-cp313-macosx_14_0_arm64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.6-cp313-cp313-macosx_11_0_arm64.whl (10.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 13.3 MB/s  0:00:00.6 MB/s eta 0:00:01:01
Downloading numpy-2.5.3-cp313-cp313-macosx_14_0_arm64.whl (5.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 9.7 MB/s  0:00:00m 10.8 MB/s eta 0:00:01
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]━━━━ 1/2 [pandas]
Successfully installed numpy-2.5.3 pandas-3.0.6

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [4]:
import pandas as pd

In [5]:
df = pd.read_csv('ventas_videojuegos.csv')

In [6]:
df.head(8)

,nombre,plataforma,genero,anio,editora,ventas_na,ventas_eu,ventas_jp,ventas_otros,ventas_global
0,The Elder Scrolls V: Skyrim,X360,Rol,2011.0,Bethesda,7.12,6.35,6.99,2.26,22.72
1,Assassin's Creed Odyssey,PS4,Accion,2018.0,Ubisoft,3.85,2.99,0.64,0.55,8.03
2,Fall Guys,PS4,Plataformas,2020.0,Devolver Digital,0.40,0.26,0.15,0.08,0.89
3,Tekken 7,PS4,Lucha,2017.0,Bandai Namco,1.09,0.90,1.10,0.33,3.42
4,It Takes Two,PS4,Aventura,2021.0,Electronic Arts,1.11,0.84,0.30,0.20,2.45
5,Super Mario World,SNES,Plataformas,1990.0,Nintendo,3.68,2.68,2.16,0.69,9.21
6,The Legend of Zelda: Tears of the Kingdom,Switch,Aventura,2023.0,Nintendo,1.72,1.42,1.01,0.41,4.56
7,Forza Motorsport 3,X360,Carreras,2009.0,Microsoft,2.00,2.34,0.42,0.65,5.41

In [7]:
df.tail()

,nombre,plataforma,genero,anio,editora,ventas_na,ventas_eu,ventas_jp,ventas_otros,ventas_global
199,Elden Ring,PS5,Rol,2022.0,Bandai Namco,2.25,1.82,2.81,0.61,7.49
200,Gran Turismo Sport,PS4,Carreras,2017.0,NaN,0.33,0.32,0.06,0.05,0.76
201,The Last of Us,PS3,Aventura,2013.0,Sony,3.09,2.00,0.87,0.41,6.37
202,Assassin's Creed II,X360,Accion,2009.0,Ubisoft,3.92,2.72,1.24,0.70,8.58
203,Call of Duty: Modern Warfare 2,X360,Disparos,2009.0,Activision,5.15,3.59,0.41,1.00,10.15

In [8]:
df.shape

(204, 10)

In [9]:
df.columns

Index(['nombre', 'plataforma', 'genero', 'anio', 'editora', 'ventas_na',
       'ventas_eu', 'ventas_jp', 'ventas_otros', 'ventas_global'],
      dtype='str')

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 204 entries, 0 to 203
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   nombre         204 non-null    str
 1   plataforma     204 non-null    str
 2   genero         204 non-null    str
 3   anio           197 non-null    float64
 4   editora        199 non-null    str
 5   ventas_na      204 non-null    float64
 6   ventas_eu      204 non-null    float64
 7   ventas_jp      204 non-null    float64
 8   ventas_otros   204 non-null    float64
 9   ventas_global  204 non-null    float64
dtypes: float64(6), str(4)
memory usage: 16.1 KB

In [11]:
df.dtypes

nombre               str
plataforma           str
genero               str
anio             float64
editora              str
ventas_na        float64
ventas_eu        float64
ventas_jp        float64
ventas_otros     float64
ventas_global    float64
dtype: object

In [12]:
df.describe()

,anio,ventas_na,ventas_eu,ventas_jp,ventas_otros,ventas_global
count,197.000000,204.000000,204.000000,204.000000,204.000000,204.000000
mean,2011.959391,3.230441,2.640833,1.513676,0.773824,8.158775
std,8.460495,2.761133,2.404268,1.749858,0.747262,7.132819
min,1985.000000,0.210000,0.150000,0.020000,0.030000,0.450000
25%,2007.000000,1.415000,1.157500,0.360000,0.317500,3.545000
50%,2015.000000,2.325000,1.855000,0.905000,0.545000,5.970000
75%,2018.000000,4.097500,3.110000,2.140000,0.957500,9.947500
max,2023.000000,14.590000,12.770000,8.380000,3.710000,31.450000

In [14]:
df.duplicated().sum()

np.int64(4)

In [15]:
df = df.drop_duplicates()

In [16]:
df.shape

(200, 10)

In [17]:
df.isnull()

,nombre,plataforma,genero,anio,editora,ventas_na,ventas_eu,ventas_jp,ventas_otros,ventas_global
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
199,False,False,False,False,False,False,False,False,False,False
200,False,False,False,False,True,False,False,False,False,False
201,False,False,False,False,False,False,False,False,False,False
202,False,False,False,False,False,False,False,False,False,False
203,False,False,False,False,False,False,False,False,False,False

In [18]:
df.isnull().sum()

nombre           0
plataforma       0
genero           0
anio             7
editora          5
ventas_na        0
ventas_eu        0
ventas_jp        0
ventas_otros     0
ventas_global    0
dtype: int64

In [19]:
df['editora'] = df['editora'].fillna('Desconocida')

In [20]:
df.isnull().sum()

nombre           0
plataforma       0
genero           0
anio             7
editora          0
ventas_na        0
ventas_eu        0
ventas_jp        0
ventas_otros     0
ventas_global    0
dtype: int64

In [21]:
df = df.dropna(subset=['anio'])

In [22]:
df.isnull().sum()

nombre           0
plataforma       0
genero           0
anio             0
editora          0
ventas_na        0
ventas_eu        0
ventas_jp        0
ventas_otros     0
ventas_global    0
dtype: int64